apiVersion: v1
kind: Service
metadata:
  name: chatui-service
spec:
  selector:
    app: chatui
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatui
spec:
  selector:
    matchLabels:
      app: chatui
  replicas: 1
  template:
    metadata:
      labels:
        app: chatui
    spec:
      containers:
        - name: chatui
          image: docker.io/srideviwijaya/chatui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
          - name: TRITON_SERVER_URL
            value: "http://10.108.165.72:8000" #update the server url