apiVersion: v1
kind: Service
metadata:
  name: chatuisss-service
spec:
  selector:
    app: chatui
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatui
spec:
  selector:
    matchLabels:
      app: chatui
  replicas: 1
  template:
    metadata:
      labels:
        app: chatui
    spec:
      containers:
        - name: chatui
          image: docker.io/srideviwijaya/chatui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000