name: "llamav2"
backend: "python"
input [
  {
    name: "prompt"
    data_type: TYPE_STRING  
    dims: [1]
  }
]
output [
  {
    name: "generated_text"
    data_type: TYPE_STRING  
    dims: [1]
  }
]
instance_group [
  {
    kind: KIND_GPU
  }
]
dynamic_batching {
    max_queue_delay_microseconds: 100
}