apiVersion: v1
kind: Pod
metadata:
  name: triton-client
spec:
  containers:
    - name: triton-client
      image: nvcr.io/nvidia/tritonserver:24.04-py3-sdk
      command: ["/bin/sh","-c"]
      args: ["perf_analyzer -m llamav2 --concurrency-range 1:4 -u http://10.96.64.169:8000"]