kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
name: gpu-hpa
spec:
scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: triton
minReplicas: 1
maxReplicas: 3
metrics:
- type: Pods
    pods:
    metricName: avg_time_queue_ms # replace with metrics to scale based on
    targetAverageValue: 50