apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
  labels:
    app: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      volumes:
      - name: local-volume
        hostPath: {
          path: /mnt/data
        }
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      containers:
        - name: triton
          ports:
          - containerPort: 8000
            name: http-triton
          - containerPort: 8001
            name: grpc-triton
          - containerPort: 8002
            name: metrics-triton
          image: docker.io/srideviwijaya/triton-server #replace with your image
          volumeMounts:
          - mountPath: /models
            name: local-volume
          - mountPath: /dev/shm
            name: dshm
          command: ["/bin/sh", "-c"]
          args: ["tritonserver --model-repository=/models --log-verbose=1"]
          resources:
            limits:
              nvidia.com/gpu: 1
